// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbturxqsuqyjohcvwoju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZidHVyeHFzdXF5am9oY3Z3b2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTQ2MjcsImV4cCI6MjA1NDc5MDYyN30.SpZ2_rk96r9AGub8yCf2-I0DWdcOMMoxdDrQu7nMXIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);